// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtaQ31CL2Q0oKkXEEhkEyEySyU8VB3pEk',
    appId: '1:69331312356:web:06dcb9f29dd509e19e96f1',
    messagingSenderId: '69331312356',
    projectId: 'fitnessquestflutter',
    authDomain: 'fitnessquestflutter.firebaseapp.com',
    storageBucket: 'fitnessquestflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfOd1k5OYy9tGpk-pBynlzKcDTM3aIncg',
    appId: '1:69331312356:android:7ab006b08eb261689e96f1',
    messagingSenderId: '69331312356',
    projectId: 'fitnessquestflutter',
    storageBucket: 'fitnessquestflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAljNrEsbSeLDCizDWEU1MkeqDbhBB3BAc',
    appId: '1:69331312356:ios:53bc429d4a04bd149e96f1',
    messagingSenderId: '69331312356',
    projectId: 'fitnessquestflutter',
    storageBucket: 'fitnessquestflutter.appspot.com',
    iosBundleId: 'com.example.fitnessquestV1',
  );
}
